config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :regions
  resources :sightings
  resources :species

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :sightings

  
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :species
  belongs_to :region

  validates :date, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :species_id, :presence => true
end

app/models/species.rb
class Species < ApplicationRecord
  validates :name, :presence => true

  has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.all
  end

  def show
    @region = Region.find(params[:id])
  end

  def new
    @region = Region.new
  end

  def edit
    @region = Region.find(params[:id])
  end

  def create
    @region = Region.new(region_params)

    if @region.save
      redirect_to @region
    else
      render 'new'
    end
  end

  def update
    @region = Region.find(params[:id])

    if @region.update(region_params)
      redirect_to @region
    else
      render 'edit'
    end
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy

    redirect_to regions_path
  end

  private
    def region_params
      params.require(:region).permit(:title, :text)
    end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def index
    @sighting = Sighting.all
    @species = Species.all
    @regions = Region.all
  end

  def show
    @sighting = Sighting.find(params[:id])
  end

  def edit
    @sighting = Sighting.find(params[:id])
    @all_regions = Region.all
  end

  def create
    @sighting = Sighting.create(params[:sightings])
    @species = Species.find(params[:sightings][:species_id])
    redirect_to @sighting
  end

  def update
    @sighting = Sighting.find(params[:id])

    if @sighting.update(sighting_params)
      redirect_to @sighting
    else
      render 'edit'
    end
  end

  def destroy
    @sightings = Sighting.find(params[:id])
    @sightings.destroy

    redirect_to sightings_path
  end

  private
    def sighting_params
      params.require(:sighting).permit(:title, :text)
    end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
    render('species/index.html.erb')
  end

  # def new
  #   @species = Species.new(params[:species])
  #   render('species/index.html.erb')
  # end

  def create
    @species = Species.create(params[:species])
    redirect_to '/species'
  end

  def edit
    @species = Species.find(params[:id])
    render('species/edit.html.erb')
  end

  def show
    @species = Species.find(params[:id])
    @all_species =Species.all
    @sightings = Sighting.all
    @all_regions = Region.all
    render('species/show.html.erb')
  end

  def update
    @species = Species.find(params[:id])
    if @species.update(params[:species])
      redirect_to '/species'
    else
      render('species/edit.html.erb')
    end
  end

  def destroy
    @species = Species.find(params[:id])
    @species.destroy
    index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regions/edit.html.erb
<h1>Edit region</h1>

<%= form_with(model: @region, local: true) do |form| %>

  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@region.errors.count, "error") %> prohibited
        this region from being saved:
      </h2>
      <ul>
        <% @region.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<h1>Listing regions</h1>

<%= link_to 'New region', new_region_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @regions.each do |region| %>
   <tr>
     <td><%= region.title %></td>
     <td><%= region.text %></td>
     <td><%= link_to 'Show', region_path(region) %></td>
     <td><%= link_to 'Edit', edit_region_path(region) %></td>
     <td><%= link_to 'Destroy', region_path(region),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
</table>

app/views/regions/new.html.erb
<h1> New Region</h1>

<%= form_with scope: :region, url: regions_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @region.title %>
</p>

<p>
  <strong>Text</strong>
  <%= @region.text %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>

app/views/sightings/edit.html.erb
<h1>Edit sighting</h1>

<%= form_with(model: @sighting, local: true) do |form| %>

  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@sighting.errors.count, "error") %> prohibited
        this region from being saved:
      </h2>
      <ul>
        <% @sighting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<h1>Listing sightings</h1>

<%= link_to 'New sighting', new_sighting_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @sighting.each do |sighting| %>
   <tr>
     <td><%= sighting.title %></td>
     <td><%= sighting.text %></td>
     <td><%= link_to 'Show', sighting_path(sighting) %></td>
     <td><%= link_to 'Edit', sighting_region_path(sighting) %></td>
     <td><%= link_to 'Destroy', sighting_path(sighting),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
</table>

app/views/sightings/new.html.erb
<h1> New Sighting</h1>

<%= form_with scope: :sighting, url: sightings_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @sighting.title %>
</p>

<p>
  <strong>Text</strong>
  <%= @sighting.text %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/species/edit.html.erb
<h1>Edit species</h1>

<%= form_with(model: @species, local: true) do |form| %>

  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@species.errors.count, "error") %> prohibited
        this region from being saved:
      </h2>
      <ul>
        <% @species.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', species_path %>

app/views/species/index.html.erb
<h1>Listing species</h1>

<%= link_to 'New species', new_species_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @species.each do |species| %>
   <tr>
     <td><%= species.title %></td>
     <td><%= species.text %></td>
     <td><%= link_to 'Show', species_path(species) %></td>
     <td><%= link_to 'Edit', species_region_path(species) %></td>
     <td><%= link_to 'Destroy', species_path(species),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
</table>

app/views/species/new.html.erb
<h1>Create new species</h1>

<form action="/species" method="post">
  <label for="new_species">New species</label>
  <input id='new_species' name="species[name]" type="text">
  <button>Create new species</button>
</form>

app/views/species/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @species.title %>
</p>

<p>
  <strong>Text</strong>
  <%= @species.text %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_path %>

app/views/welcome/index.html.erb
<h1>Welcome to your Wildlife Tracker</h1>
<%= link_to 'My Tracker', controller: 'regions' %>